import {
  Establecimiento,
  Campana,
  Lote,
  Labor,
  TimelineEvent,
  RegistroLluvia,
  ResumenEconomico,
  Maquinaria,
} from "./types";

export const ESTABLECIMIENTO_ACTUAL: Establecimiento = {
  id: "est-1",
  nombre: "Establecimiento La Posta",
  titular: "Gabriel Borgogno",
  ubicacion: "Marcos Juárez, Córdoba, Argentina",
  superficie_total: 1125,
  latitud: -32.6961,
  longitud: -62.1067,
};

export const CAMPANAS_MOCK: Campana[] = [
  {
    id: "camp-2025-26",
    nombre: "Campaña 2025/26",
    fecha_inicio: "01/07/2025",
    fecha_fin: "Actualidad",
    activa: true,
  },
  {
    id: "camp-2024-25",
    nombre: "Campaña 2024/25",
    fecha_inicio: "01/07/2024",
    fecha_fin: "30/06/2025",
    activa: false,
  },
  {
    id: "camp-2023-24",
    nombre: "Campaña 2023/24",
    fecha_inicio: "01/07/2023",
    fecha_fin: "30/06/2024",
    activa: false,
  },
];

// 18 lotes matching the mockup layout and numbers
export const LOTES_MOCK: Lote[] = [
  {
    id: "lote-1",
    numero: 1,
    nombre: "Lote 1",
    hectareas: 125,
    cultivo_actual: "Maíz",
    variedad_hibrido: "DK 72-10 VT3P",
    fecha_siembra: "2025-09-18",
    rendimiento_estimado: 105,
    rendimiento_historico: 98,
    isl_score: 92,
    isl_resumen: "Excelente implantación y uniformidad. Buen estado hídrico.",
    isl_recomendacion: "Mantener plan de nutrición y monitorear orugas.",
    estado_fenologico: "R2 (Cuaje / Grano acuoso)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 38, y: 15 },
        { x: 48, y: 15 },
        { x: 48, y: 35 },
        { x: 38, y: 35 },
      ],
      center: { x: 43, y: 25 },
    },
    dose_data: {
      promedio_aplicado: 78500,
      precision_porcentaje: 97.4,
      unidad: "semillas/ha",
      points: [],
    },
  },
  {
    id: "lote-2",
    numero: 2,
    nombre: "Lote 2",
    hectareas: 102,
    cultivo_actual: "Soja",
    variedad_hibrido: "DM 46i20 IPRO",
    fecha_siembra: "2025-10-25",
    rendimiento_estimado: 42,
    rendimiento_historico: 39,
    isl_score: 88,
    isl_resumen: "Buena cobertura foliar, nodulación activa sin plagas.",
    isl_recomendacion: "Monitoreo preventivo de chinches al cierre del entresurco.",
    estado_fenologico: "R3 (Inicio de vaina)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 49, y: 12 },
        { x: 58, y: 12 },
        { x: 58, y: 32 },
        { x: 49, y: 32 },
      ],
      center: { x: 53.5, y: 22 },
    },
    dose_data: {
      promedio_aplicado: 340000,
      precision_porcentaje: 98.1,
      unidad: "semillas/ha",
      points: [],
    },
  },
  {
    id: "lote-3",
    numero: 3,
    nombre: "Lote 3",
    hectareas: 85,
    cultivo_actual: "Maíz",
    variedad_hibrido: "NK 890 VIP3",
    fecha_siembra: "2025-09-22",
    rendimiento_estimado: 98,
    rendimiento_historico: 92,
    isl_score: 90,
    isl_resumen: "Gran desarrollo radicular y vigor híbrido constante.",
    isl_recomendacion: "Evaluación de fungicida foliar en hoja de la espiga.",
    estado_fenologico: "R1 (Floración / Estigmas)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 48, y: 33 },
        { x: 62, y: 33 },
        { x: 60, y: 48 },
        { x: 48, y: 48 },
      ],
      center: { x: 54, y: 40 },
    },
    dose_data: {
      promedio_aplicado: 76000,
      precision_porcentaje: 96.8,
      unidad: "semillas/ha",
      points: [],
    },
  },
  {
    id: "lote-4",
    numero: 4,
    nombre: "Lote 4",
    hectareas: 110,
    cultivo_actual: "Soja",
    variedad_hibrido: "SY 4x1 Enlist",
    fecha_siembra: "2025-11-02",
    rendimiento_estimado: 34,
    rendimiento_historico: 41,
    isl_score: 64,
    isl_resumen: "Menor lluvia en floración (-58 mm) y menor dosis de nitrógeno.",
    isl_recomendacion: "Ajustar esquema de fertilización para la próxima campaña.",
    estado_fenologico: "R4 (Vaina desarrollada)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 28, y: 46 },
        { x: 42, y: 46 },
        { x: 40, y: 64 },
        { x: 26, y: 64 },
      ],
      center: { x: 34, y: 55 },
    },
    dose_data: {
      promedio_aplicado: 44100,
      precision_porcentaje: 95.82,
      unidad: "semillas/ha",
      points: [],
    },
  },
  {
    id: "lote-5",
    numero: 5,
    nombre: "Lote 5",
    hectareas: 95,
    cultivo_actual: "Maíz",
    variedad_hibrido: "DK 72-10 VT3P",
    fecha_siembra: "2025-09-28",
    rendimiento_estimado: 108,
    rendimiento_historico: 101,
    isl_score: 95,
    isl_resumen: "Excelente implantación y respuesta a dosis variable.",
    isl_recomendacion: "Mantener plan nutricional estándar.",
    estado_fenologico: "R2 (Cuaje)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 42, y: 49 },
        { x: 56, y: 49 },
        { x: 54, y: 66 },
        { x: 40, y: 66 },
      ],
      center: { x: 48, y: 57 },
    },
    dose_data: {
      promedio_aplicado: 80000,
      precision_porcentaje: 98.6,
      unidad: "semillas/ha",
      points: [],
    },
  },
  {
    id: "lote-6",
    numero: 6,
    nombre: "Lote 6",
    hectareas: 78,
    cultivo_actual: "Maíz",
    variedad_hibrido: "NK 842 VIP3",
    fecha_siembra: "2025-10-04",
    rendimiento_estimado: 102,
    rendimiento_historico: 96,
    isl_score: 91,
    isl_resumen: "Estructura de cultivo óptima.",
    isl_recomendacion: "Seguimiento satelital NDVI.",
    estado_fenologico: "V12 (Doce hojas)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 58, y: 15 },
        { x: 68, y: 15 },
        { x: 68, y: 35 },
        { x: 58, y: 35 },
      ],
      center: { x: 63, y: 25 },
    },
  },
  {
    id: "lote-7",
    numero: 7,
    nombre: "Lote 7",
    hectareas: 65,
    cultivo_actual: "Maíz",
    variedad_hibrido: "DK 73-20 TRE",
    fecha_siembra: "2025-09-15",
    rendimiento_estimado: 112,
    rendimiento_historico: 104,
    isl_score: 94,
    isl_resumen: "Punta de rinde del establecimiento. Suelo tipo I.",
    isl_recomendacion: "Lote testigo de máxima producción.",
    estado_fenologico: "R3 (Grano lechoso)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 25, y: 28 },
        { x: 37, y: 28 },
        { x: 37, y: 45 },
        { x: 25, y: 45 },
      ],
      center: { x: 31, y: 36 },
    },
  },
  {
    id: "lote-8",
    numero: 8,
    nombre: "Lote 8",
    hectareas: 80,
    cultivo_actual: "Maíz",
    variedad_hibrido: "DK 72-10 VT3P",
    fecha_siembra: "2025-09-20",
    rendimiento_estimado: 100,
    rendimiento_historico: 95,
    isl_score: 89,
    isl_resumen: "Fertilización nitrogenada completada con éxito.",
    isl_recomendacion: "Esperar 10 días para evaluar respuesta foliar.",
    estado_fenologico: "V10 (Diez hojas)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 62, y: 36 },
        { x: 74, y: 36 },
        { x: 72, y: 55 },
        { x: 60, y: 55 },
      ],
      center: { x: 67, y: 45 },
    },
  },
  {
    id: "lote-9",
    numero: 9,
    nombre: "Lote 9",
    hectareas: 70,
    cultivo_actual: "Soja",
    variedad_hibrido: "DM 40R21",
    fecha_siembra: "2025-10-28",
    rendimiento_estimado: 40,
    rendimiento_historico: 38,
    isl_score: 87,
    isl_resumen: "Crecimiento uniforme sin malezas resistentes.",
    isl_recomendacion: "Monitoreo semanal de oruga medidora.",
    estado_fenologico: "R2 (Floración plena)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 15, y: 30 },
        { x: 25, y: 30 },
        { x: 25, y: 50 },
        { x: 15, y: 50 },
      ],
      center: { x: 20, y: 40 },
    },
  },
  {
    id: "lote-10",
    numero: 10,
    nombre: "Lote 10",
    hectareas: 55,
    cultivo_actual: "Maíz",
    variedad_hibrido: "NK 890 VIP3",
    fecha_siembra: "2025-10-02",
    rendimiento_estimado: 97,
    rendimiento_historico: 93,
    isl_score: 86,
    isl_resumen: "Buena stand de plantas.",
    isl_recomendacion: "Revisar humedad en perfil profundo.",
    estado_fenologico: "V8 (Ocho hojas)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 54, y: 56 },
        { x: 66, y: 56 },
        { x: 64, y: 75 },
        { x: 52, y: 75 },
      ],
      center: { x: 59, y: 65 },
    },
  },
  {
    id: "lote-11",
    numero: 11,
    nombre: "Lote 11",
    hectareas: 60,
    cultivo_actual: "Maíz",
    variedad_hibrido: "DK 72-10 VT3P",
    fecha_siembra: "2025-10-01",
    rendimiento_estimado: 99,
    rendimiento_historico: 94,
    isl_score: 88,
    isl_resumen: "Buen porte agronómico.",
    isl_recomendacion: "Mantener rotación planificada.",
    estado_fenologico: "V9 (Nueve hojas)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 38, y: 35 },
        { x: 48, y: 35 },
        { x: 48, y: 49 },
        { x: 38, y: 49 },
      ],
      center: { x: 43, y: 42 },
    },
  },
  {
    id: "lote-12",
    numero: 12,
    nombre: "Lote 12",
    hectareas: 58,
    cultivo_actual: "Trigo",
    variedad_hibrido: "Baguette 620",
    fecha_siembra: "2025-06-10",
    rendimiento_estimado: 48,
    rendimiento_historico: 44,
    isl_score: 92,
    isl_resumen: "Cosecha finalizando con rindes excepcionales (+8%).",
    isl_recomendacion: "Planificar siembra de soja de segunda inmediata.",
    estado_fenologico: "Madurez de cosecha (13.5% humedad)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 46, y: 6 },
        { x: 56, y: 6 },
        { x: 56, y: 15 },
        { x: 46, y: 15 },
      ],
      center: { x: 51, y: 10.5 },
    },
  },
  {
    id: "lote-13",
    numero: 13,
    nombre: "Lote 13",
    hectareas: 45,
    cultivo_actual: "Trigo",
    variedad_hibrido: "Klein Serpiente",
    fecha_siembra: "2025-06-14",
    rendimiento_estimado: 45,
    rendimiento_historico: 42,
    isl_score: 89,
    isl_resumen: "Cosecha completada sin pérdidas por espigado.",
    isl_recomendacion: "Pulverización de barbecho corto para soja 2da.",
    estado_fenologico: "Cosechado",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 68, y: 25 },
        { x: 80, y: 25 },
        { x: 78, y: 40 },
        { x: 66, y: 40 },
      ],
      center: { x: 73, y: 32 },
    },
  },
  {
    id: "lote-14",
    numero: 14,
    nombre: "Lote 14",
    hectareas: 42,
    cultivo_actual: "Girasol",
    variedad_hibrido: "Paraiso 102 CL",
    fecha_siembra: "2025-10-10",
    rendimiento_estimado: 28,
    rendimiento_historico: 26,
    isl_score: 85,
    isl_resumen: "Excelente capítulo y uniformidad de floración.",
    isl_recomendacion: "Monitoreo de aves en borde de monte.",
    estado_fenologico: "R5 (Floración)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 66, y: 42 },
        { x: 78, y: 42 },
        { x: 76, y: 58 },
        { x: 64, y: 58 },
      ],
      center: { x: 71, y: 50 },
    },
  },
  {
    id: "lote-15",
    numero: 15,
    nombre: "Lote 15",
    hectareas: 38,
    cultivo_actual: "Soja",
    variedad_hibrido: "DM 46i20",
    fecha_siembra: "2025-11-05",
    rendimiento_estimado: 38,
    rendimiento_historico: 36,
    isl_score: 84,
    isl_resumen: "Buen desarrollo vegetativo.",
    isl_recomendacion: "Evaluar segunda aplicación de herbicida.",
    estado_fenologico: "V4 (Cuatro nudos)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 56, y: 42 },
        { x: 66, y: 42 },
        { x: 64, y: 56 },
        { x: 54, y: 56 },
      ],
      center: { x: 60, y: 49 },
    },
  },
  {
    id: "lote-16",
    numero: 16,
    nombre: "Lote 16",
    hectareas: 32,
    cultivo_actual: "Soja",
    variedad_hibrido: "SY 4x1 Enlist",
    fecha_siembra: "2025-11-08",
    rendimiento_estimado: 37,
    rendimiento_historico: 35,
    isl_score: 83,
    isl_resumen: "Emergencia pareja.",
    isl_recomendacion: "Control de malezas en cabeceras.",
    estado_fenologico: "V3 (Tres nudos)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 42, y: 66 },
        { x: 54, y: 66 },
        { x: 50, y: 82 },
        { x: 38, y: 82 },
      ],
      center: { x: 46, y: 74 },
    },
  },
  {
    id: "lote-17",
    numero: 17,
    nombre: "Lote 17",
    hectareas: 30,
    cultivo_actual: "Maíz",
    variedad_hibrido: "DK 72-10",
    fecha_siembra: "2025-09-30",
    rendimiento_estimado: 103,
    rendimiento_historico: 97,
    isl_score: 93,
    isl_resumen: "Muy buena coloración y sanidad.",
    isl_recomendacion: "Monitoreo normal de plagas.",
    estado_fenologico: "V11 (Once hojas)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 26, y: 64 },
        { x: 38, y: 64 },
        { x: 35, y: 80 },
        { x: 23, y: 80 },
      ],
      center: { x: 30, y: 72 },
    },
  },
  {
    id: "lote-18",
    numero: 18,
    nombre: "Lote 18",
    hectareas: 29,
    cultivo_actual: "Maíz",
    variedad_hibrido: "NK 890 VIP3",
    fecha_siembra: "2025-10-03",
    rendimiento_estimado: 95,
    rendimiento_historico: 90,
    isl_score: 87,
    isl_resumen: "Lote perimetral con cortina forestal.",
    isl_recomendacion: "Control de daño de cotorras en bordes.",
    estado_fenologico: "V9 (Nueve hojas)",
    establecimiento_id: "est-1",
    campana_id: "camp-2025-26",
    map_coords: {
      polygon: [
        { x: 48, y: 70 },
        { x: 58, y: 70 },
        { x: 54, y: 86 },
        { x: 44, y: 86 },
      ],
      center: { x: 51, y: 78 },
    },
  },
];

export const LABORES_MOCK: Labor[] = [
  {
    id: "lab-1",
    tipo: "Fertilización",
    lote_id: "lote-8",
    lote_nombre: "Lote 8 - Maíz",
    cultivo: "Maíz",
    fecha: "2026-07-30",
    estado: "Completada",
    superficie_ha: 80,
    insumo_principal: "SolMix / UREA granulada",
    dosis: "220 kg/ha",
    maquinaria: "Fertilizadora Metalfor F-3000",
    operario: "Carlos Benítez",
    costo_estimado: 14800,
    observaciones: "Aplicación variable según mapa de prescripción.",
    campana_id: "camp-2025-26",
  },
  {
    id: "lab-2",
    tipo: "Siembra",
    lote_id: "lote-5",
    lote_nombre: "Lote 5 - Maíz",
    cultivo: "Maíz",
    fecha: "2026-07-28",
    estado: "Completada",
    superficie_ha: 95,
    insumo_principal: "DK 72-10 VT3P + MAP",
    dosis: "80.000 sem/ha + 110 kg MAP/ha",
    maquinaria: "Sembradora John Deere DB60",
    operario: "Roberto Giménez",
    costo_estimado: 28500,
    observaciones: "Condiciones de humedad óptimas a 5 cm.",
    campana_id: "camp-2025-26",
  },
  {
    id: "lab-3",
    tipo: "Pulverización",
    lote_id: "lote-2",
    lote_nombre: "Lote 2 - Soja",
    cultivo: "Soja",
    fecha: "2026-07-27",
    estado: "Completada",
    superficie_ha: 102,
    insumo_principal: "Herbicida residual + Coadyuvante",
    dosis: "1.8 lts/ha",
    maquinaria: "Pulverizadora PLA MAP 3300",
    operario: "Carlos Benítez",
    costo_estimado: 9200,
    observaciones: "Viento 8 km/h, humedad relativa 68%.",
    campana_id: "camp-2025-26",
  },
  {
    id: "lab-4",
    tipo: "Cosecha",
    lote_id: "lote-12",
    lote_nombre: "Lote 12 - Trigo",
    cultivo: "Trigo",
    fecha: "2026-07-25",
    estado: "En progreso",
    superficie_ha: 58,
    insumo_principal: "Trigo Baguette 620",
    dosis: "Rinde promedio 48 qq/ha",
    maquinaria: "Cosechadora Case IH 8250 + Draper 40ft",
    operario: "Contratista Don Pedro",
    costo_estimado: 7500,
    observaciones: "Humedad de recibo 13.2%. Avance 75%.",
    campana_id: "camp-2025-26",
  },
  {
    id: "lab-5",
    tipo: "Monitoreo",
    lote_id: "lote-4",
    lote_nombre: "Lote 4 - Soja",
    cultivo: "Soja",
    fecha: "2026-08-10",
    estado: "Pendiente",
    superficie_ha: 110,
    insumo_principal: "Relevamiento de plagas y estrés hídrico",
    dosis: "10 estaciones de muestreo",
    maquinaria: "Pickup 4x4 + Sensor NDVI",
    operario: "Ing. Agr. Lucas Varela",
    costo_estimado: 850,
    observaciones: "Puntualizar en sectores de bajo rinde histórico.",
    campana_id: "camp-2025-26",
  },
  {
    id: "lab-6",
    tipo: "Fertilización",
    lote_id: "lote-1",
    lote_nombre: "Lote 1 - Maíz",
    cultivo: "Maíz",
    fecha: "2026-08-15",
    estado: "Pendiente",
    superficie_ha: 125,
    insumo_principal: "UAN Líquido",
    dosis: "180 lts/ha",
    maquinaria: "Pulverizadora PLA MAP 3300",
    operario: "Carlos Benítez",
    costo_estimado: 18200,
    observaciones: "Re-fertilización nitrogenada en V6.",
    campana_id: "camp-2025-26",
  },
];

export const TIMELINE_MOCK: Record<string, TimelineEvent[]> = {
  "lote-4": [
    {
      id: "tl-4-1",
      lote_id: "lote-4",
      fecha: "02 Nov 2025",
      tipo: "siembra",
      titulo: "Siembra Soja 1ra",
      descripcion: "Variedad SY 4x1 Enlist a 52 cm. Dosis promedio 44.100 sem/ha.",
      datos_clave: [
        { etiqueta: "Dosis", valor: "44.100 sem/ha" },
        { etiqueta: "Velocidad", valor: "7.2 km/h" },
        { etiqueta: "Precisión", valor: "95.82%" },
      ],
      autor: "Roberto Giménez (JD DB60)",
    },
    {
      id: "tl-4-2",
      lote_id: "lote-4",
      fecha: "18 Nov 2025",
      tipo: "fertilizacion",
      titulo: "Fertilización de arranque",
      descripcion: "Aplicación de Microessentials SZ en línea de siembra.",
      datos_clave: [{ etiqueta: "Dosis", valor: "85 kg/ha" }],
      autor: "Carlos Benítez",
    },
    {
      id: "tl-4-3",
      lote_id: "lote-4",
      fecha: "04 Dic 2025",
      tipo: "lluvia",
      titulo: "Lluvia registrada (35 mm)",
      descripcion: "Precipitación mansa durante 14 horas. Excelente infiltración.",
      datos_clave: [{ etiqueta: "Milímetros", valor: "35 mm" }],
      autor: "Pluviómetro Estación Sur",
    },
    {
      id: "tl-4-4",
      lote_id: "lote-4",
      fecha: "20 Dic 2025",
      tipo: "pulverizacion",
      titulo: "Pulverización herbicida post-emergente",
      descripcion: "Glifosato + Enlist Colex-D para control de Yuyo Colorado.",
      datos_clave: [{ etiqueta: "Volumen caldo", valor: "60 lts/ha" }],
      autor: "PLA MAP 3300",
    },
    {
      id: "tl-4-5",
      lote_id: "lote-4",
      fecha: "08 Ene 2026",
      tipo: "helada",
      titulo: "Estrés térmico y déficit hídrico",
      descripcion: "Ola de calor persistente con temperaturas >38°C durante floración.",
      datos_clave: [
        { etiqueta: "Déficit lluvia", valor: "-58 mm vs histórico" },
        { etiqueta: "Temp. Promedio", valor: "+2.1°C" },
      ],
      autor: "Estación Meteorológica Automática",
    },
    {
      id: "tl-4-6",
      lote_id: "lote-4",
      fecha: "22 Ene 2026",
      tipo: "fungicida",
      titulo: "Aplicación fungicida preventivo",
      descripcion: "Carboxamida + Triazol para mancha marrón y tizón.",
      datos_clave: [{ etiqueta: "Estado", valor: "R3 avanzado" }],
      autor: "Aeroaplicador Los Pinos",
    },
    {
      id: "tl-4-7",
      lote_id: "lote-4",
      fecha: "15 Jul 2026",
      tipo: "informe_ia",
      titulo: "Diagnóstico Lía IA: Rendimiento y Pérdida",
      descripcion:
        "Analicé los datos del Lote 4: menor lluvia en floración (-58 mm) y menor dosis de nitrógeno (-40 kg/ha) causaron merma del 17% vs histórico.",
      datos_clave: [
        { etiqueta: "ISL Actual", valor: "64/100" },
        { etiqueta: "Acción sugerida", valor: "Rotación a maíz + fósforo" },
      ],
      autor: "Lía Asistente Inteligente",
    },
  ],
};

export const LLUVIAS_MOCK: RegistroLluvia[] = [
  {
    id: "lluv-1",
    fecha: "2026-08-22",
    milimetros: 18,
    lote_nombre: "General Establecimiento",
    observaciones: "Lluvia general hace 4 días. Muy oportuna para maíz de primera.",
    campana_id: "camp-2025-26",
  },
  {
    id: "lluv-2",
    fecha: "2026-08-04",
    milimetros: 32,
    lote_nombre: "Zona Norte (Lotes 1 a 6)",
    observaciones: "Lluvia de frente sur con viento calmo.",
    campana_id: "camp-2025-26",
  },
  {
    id: "lluv-3",
    fecha: "2026-07-19",
    milimetros: 45,
    lote_nombre: "General Establecimiento",
    observaciones: "Excelente recarga en perfil de 1 metro.",
    campana_id: "camp-2025-26",
  },
  {
    id: "lluv-4",
    fecha: "2026-06-28",
    milimetros: 12,
    lote_nombre: "General Establecimiento",
    observaciones: "Llovizna persistente durante la noche.",
    campana_id: "camp-2025-26",
  },
];

export const ECONOMIA_MOCK: ResumenEconomico = {
  campana_id: "camp-2025-26",
  ingresos_totales: 768450,
  gastos_totales: 443870,
  margen_bruto: 324580,
  margen_por_ha: 288,
  distribucion_gastos: [
    { categoria: "Insumos", monto: 186425, porcentaje: 42, color: "#4F8A3F" },
    { categoria: "Labores", monto: 110967, porcentaje: 25, color: "#10B981" },
    { categoria: "Semillas", monto: 66580, porcentaje: 15, color: "#F59E0B" },
    { categoria: "Flete", monto: 44387, porcentaje: 10, color: "#F97316" },
    { categoria: "Otros", monto: 35511, porcentaje: 8, color: "#64748B" },
  ],
};

export const MAQUINARIAS_MOCK: Maquinaria[] = [
  {
    id: "maq-1",
    nombre: "John Deere 8370R",
    tipo: "Tractor",
    modelo: "2022 - 370 HP",
    estado: "Operativa",
    horas_uso: 1420,
    ubicacion_actual: "Galpón Principal",
  },
  {
    id: "maq-2",
    nombre: "John Deere DB60 (24 líneas)",
    tipo: "Sembradora",
    modelo: "2023 - Dosificación Neumática ExactEmerge",
    estado: "Operativa",
    horas_uso: 680,
    ubicacion_actual: "Lote 5",
  },
  {
    id: "maq-3",
    nombre: "PLA MAP 3300",
    tipo: "Pulverizadora",
    modelo: "2021 - Botalón fibra 36m",
    estado: "En labor",
    horas_uso: 2150,
    ubicacion_actual: "Lote 2",
  },
  {
    id: "maq-4",
    nombre: "Case IH Axial-Flow 8250",
    tipo: "Cosechadora",
    modelo: "2024 - Draper 40ft Automation",
    estado: "En labor",
    horas_uso: 310,
    ubicacion_actual: "Lote 12",
  },
];

export const LIA_SUGGESTED_PROMPTS = [
  "¿Por qué el lote 4 rindió menos?",
  "Comparar rendimiento 2024 vs 2025",
  "Recomendaciones de fertilización",
  "Contame qué pasó en el lote 7",
  "¿Cuánto llevamos invertido en insumos?",
  "Resumen de lluvias del último trimestre",
];
